### ISSUE TITLE
System.Text.Json.7.0.3 - Outdated - Vulnerable

### ISSUE THREAD

**Issue by guyulmaz** [nventive/Uno.UITests.Helpers#1]
UnoApp1.UITests.csproj, net8.0
------------------------------
System.Text.Json.7.0.3 - Outdated - Vulnerable: [ Severity: 2, https://github.com/advisories/GHSA-hh2w-p6rv-4g7w ]
    Uno.UITest.Selenium.1.1.0-dev.70
        Uno.UITest.Helpers.1.1.0-dev.70

**Comment by jeromelaban** [comment]
Thanks for the report. This is a library consumer side issue, not a library producer issue. If you get this message, you can upgrade this package in your app or library directly. This is somehow related to https://github.com/NuGet/Home/issues/7344#issuecomment-2311075251.
